# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubuto < Formula
  desc "CLI for Kubernetes Helm/GitOps chart version compatibility checks"
  homepage "https://github.com/akshatsinha007/kubuto"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/akshatsinha007/kubuto/releases/download/v0.1.0/kubuto_0.1.0_darwin_amd64.tar.gz"
      sha256 "7de2d6307abbbba1e00007c3ad0087c875d4939a68e58c92f82a88e88a5b6785"

      define_method(:install) do
        bin.install "kubuto"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/akshatsinha007/kubuto/releases/download/v0.1.0/kubuto_0.1.0_darwin_arm64.tar.gz"
      sha256 "23fb731de16984be7584bdc3b8cf8aa5aa77ed7c3818c1c994d9bf5b22f12429"

      define_method(:install) do
        bin.install "kubuto"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/akshatsinha007/kubuto/releases/download/v0.1.0/kubuto_0.1.0_linux_amd64.tar.gz"
      sha256 "708af4380abcfbf6d46a00d103ee2170813ae603b95ca90a4143a9d4635cdb8a"
      define_method(:install) do
        bin.install "kubuto"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/akshatsinha007/kubuto/releases/download/v0.1.0/kubuto_0.1.0_linux_arm64.tar.gz"
      sha256 "b1432b06b43587aa91515c20e214b25b7991ff5595a266258030ed2e79f11284"
      define_method(:install) do
        bin.install "kubuto"
      end
    end
  end

  test do
    system "#{bin}/kubuto --version"
  end
end
