# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubuto < Formula
  desc "CLI for Kubernetes Helm/GitOps chart version compatibility checks"
  homepage "https://github.com/akshatsinha007/kubuto"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/akshatsinha007/kubuto/releases/download/v0.1.0/kubuto_0.1.0_darwin_amd64.tar.gz"
      sha256 "a50bd03534964b5b971a606b0126b282ac485c69bf9cc7a80a16239abbbb1939"

      define_method(:install) do
        bin.install "kubuto"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/akshatsinha007/kubuto/releases/download/v0.1.0/kubuto_0.1.0_darwin_arm64.tar.gz"
      sha256 "23fd9a69babb3c313cd294f00296c27439f147262fd06be6eb0a7aeb57504ff4"

      define_method(:install) do
        bin.install "kubuto"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/akshatsinha007/kubuto/releases/download/v0.1.0/kubuto_0.1.0_linux_amd64.tar.gz"
      sha256 "5f5f2f83f09eec854f2978f291b08a22257cba38a19f80c43e469695cf203bb5"
      define_method(:install) do
        bin.install "kubuto"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/akshatsinha007/kubuto/releases/download/v0.1.0/kubuto_0.1.0_linux_arm64.tar.gz"
      sha256 "e5f595ba11f6530979536a901959e00013a177c98f3379fd3cedd097b25294a2"
      define_method(:install) do
        bin.install "kubuto"
      end
    end
  end

  test do
    system "#{bin}/kubuto --version"
  end
end
