# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubuto < Formula
  desc "CLI for Kubernetes Helm/GitOps chart version compatibility checks"
  homepage "https://github.com/akshatsinha007/kubuto"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/akshatsinha007/kubuto/releases/download/v0.1.0/kubuto_0.1.0_darwin_amd64.tar.gz"
      sha256 "1fbc6915c28c0d7b91f59de326a522dbed8a100042695f29efc6e785fe27b9b6"

      define_method(:install) do
        bin.install "kubuto"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/akshatsinha007/kubuto/releases/download/v0.1.0/kubuto_0.1.0_darwin_arm64.tar.gz"
      sha256 "63d6662a63597d2f7b989c2c31d9a02852b22f31b744cf24003368c9fad46daa"

      define_method(:install) do
        bin.install "kubuto"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/akshatsinha007/kubuto/releases/download/v0.1.0/kubuto_0.1.0_linux_amd64.tar.gz"
      sha256 "ec8e637c61ee89554b791c9f71f61033ce8019bf1c4d3380de58404484ea427c"
      define_method(:install) do
        bin.install "kubuto"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/akshatsinha007/kubuto/releases/download/v0.1.0/kubuto_0.1.0_linux_arm64.tar.gz"
      sha256 "9030429708d0bcec0df6085ad74faae5eea0693480ae1f8f7a57ea24a0c596b2"
      define_method(:install) do
        bin.install "kubuto"
      end
    end
  end

  test do
    system "#{bin}/kubuto --version"
  end
end
